#!/usr/bin/env ruby

prefix = 'MAME'
branchname = `git branch --no-color 2> /dev/null`[/^\* (.+)/, 1]
ticket_number = branchname.to_s.match(/\A#{prefix}-(\d+)/) && $1

exit unless ticket_number

message_file = ARGV[0]
message = File.read(message_file)

exit if message.include?("#{prefix}-#{ticket_number}")

message.strip!

if message.include?("#noref")
  message.sub!(/^\s*#noref\s*|\s*#noref/, '')
else
  message.sub!(/([^[:punct:]])\z/, "\\1.")
  message = ["#{prefix}-#{ticket_number}", message,].join(": ")
  puts message
end

File.open(message_file, 'w') {|f| f.write message }
